/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowsRouteImport } from './routes/shows'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ContextRouteImport } from './routes/context'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowsIdRouteImport } from './routes/shows.$id'
import { Route as ShowsIdSettleRouteImport } from './routes/shows.$id.settle'

const ShowsRoute = ShowsRouteImport.update({
  id: '/shows',
  path: '/shows',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextRoute = ContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowsIdRoute = ShowsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShowsRoute,
} as any)
const ShowsIdSettleRoute = ShowsIdSettleRouteImport.update({
  id: '/settle',
  path: '/settle',
  getParentRoute: () => ShowsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRoute
  '/context': typeof ContextRoute
  '/reports': typeof ReportsRoute
  '/shows': typeof ShowsRouteWithChildren
  '/shows/$id': typeof ShowsIdRouteWithChildren
  '/shows/$id/settle': typeof ShowsIdSettleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRoute
  '/context': typeof ContextRoute
  '/reports': typeof ReportsRoute
  '/shows': typeof ShowsRouteWithChildren
  '/shows/$id': typeof ShowsIdRouteWithChildren
  '/shows/$id/settle': typeof ShowsIdSettleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRoute
  '/context': typeof ContextRoute
  '/reports': typeof ReportsRoute
  '/shows': typeof ShowsRouteWithChildren
  '/shows/$id': typeof ShowsIdRouteWithChildren
  '/shows/$id/settle': typeof ShowsIdSettleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artists'
    | '/context'
    | '/reports'
    | '/shows'
    | '/shows/$id'
    | '/shows/$id/settle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artists'
    | '/context'
    | '/reports'
    | '/shows'
    | '/shows/$id'
    | '/shows/$id/settle'
  id:
    | '__root__'
    | '/'
    | '/artists'
    | '/context'
    | '/reports'
    | '/shows'
    | '/shows/$id'
    | '/shows/$id/settle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistsRoute: typeof ArtistsRoute
  ContextRoute: typeof ContextRoute
  ReportsRoute: typeof ReportsRoute
  ShowsRoute: typeof ShowsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context': {
      id: '/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof ContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shows/$id': {
      id: '/shows/$id'
      path: '/$id'
      fullPath: '/shows/$id'
      preLoaderRoute: typeof ShowsIdRouteImport
      parentRoute: typeof ShowsRoute
    }
    '/shows/$id/settle': {
      id: '/shows/$id/settle'
      path: '/settle'
      fullPath: '/shows/$id/settle'
      preLoaderRoute: typeof ShowsIdSettleRouteImport
      parentRoute: typeof ShowsIdRoute
    }
  }
}

interface ShowsIdRouteChildren {
  ShowsIdSettleRoute: typeof ShowsIdSettleRoute
}

const ShowsIdRouteChildren: ShowsIdRouteChildren = {
  ShowsIdSettleRoute: ShowsIdSettleRoute,
}

const ShowsIdRouteWithChildren =
  ShowsIdRoute._addFileChildren(ShowsIdRouteChildren)

interface ShowsRouteChildren {
  ShowsIdRoute: typeof ShowsIdRouteWithChildren
}

const ShowsRouteChildren: ShowsRouteChildren = {
  ShowsIdRoute: ShowsIdRouteWithChildren,
}

const ShowsRouteWithChildren = ShowsRoute._addFileChildren(ShowsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistsRoute: ArtistsRoute,
  ContextRoute: ContextRoute,
  ReportsRoute: ReportsRoute,
  ShowsRoute: ShowsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
